In [1]:
%load_ext autoreload
%autoreload 2

import dataduit as dd

In [2]:
from tfd_dev import conf_dict
conf_dict

{'meta': {'name': 'xist',
  'root_location': '../datasets',
  'logging': {'log_stream_level': 'INFO'},
  'in': {'from': 'online', 'type': 'records', 'location': '<location>'}},
 'read': {'from_stage': 'preprocessed',
  'split_percents': [75, 15, 10],
  'split_names': ['train', 'val', 'test'],
  'iterate': {'schema': {'x': {'identifier': {'in': 'image'},
     'datatype': {'in': 'int64', 'out': {}},
     'shape': {'in': {'dim': [28, 28, 1]}, 'out': {}},
     'missing': {'skip_row': True, 'log': True, 'create_mask': True}},
    'y': {'identifier': {'in': 'label'},
     'datatype': {'in': {}, 'out': {}},
     'shape': {'in': {}, 'out': {}},
     'missing': {'skip_row': True, 'log': True, 'create_mask': True}}}}}}

In [4]:
ds_dict = dd.read(conf_dict)

../datasets/xist/preprocessed


NotImplementedError: read_tf_from_dir() not implemented yet

In [8]:
ds_dict

{'train': <PrefetchDataset shapes: ((28, 28, 1), ()), types: (tf.uint8, tf.int64)>,
 'val': <PrefetchDataset shapes: ((28, 28, 1), ()), types: (tf.uint8, tf.int64)>,
 'test': <PrefetchDataset shapes: ((28, 28, 1), ()), types: (tf.uint8, tf.int64)>}

In [10]:
tds = ds_dict['train']

In [11]:
sing = tds.take(1)

In [17]:
for x,y in sing:
    print(x)
    print(y)

tf.Tensor(
[[[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  