In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import dataduit as dd

In [10]:
from tfd_dev import conf_dict
conf_dict

{'meta': {'name': 'mnist',
  'root_location': '../datasets',
  'logging': {'log_stream_level': 'INFO'},
  'in': {'from': 'online', 'type': 'tfd', 'location': '<location>'}},
 'read': {'from': 'preprocessed',
  'split_percents': [75, 15, 10],
  'split_names': ['train', 'val', 'test'],
  'iterate': {'schema': {'x': {'identifier': {'in': 'image'},
     'datatype': {'in': 'int64', 'out': {}},
     'shape': {'in': {'dim': [28, 28, 1]}, 'out': {}},
     'missing': {'skip_row': True, 'log': True, 'create_mask': True}},
    'y': {'identifier': {'in': 'label'},
     'datatype': {'in': {}, 'out': {}},
     'shape': {'in': {}, 'out': {}},
     'missing': {'skip_row': True, 'log': True, 'create_mask': True}}}}}}

In [11]:
od = dd.info(conf_dict)

In [12]:
od

tfds.core.DatasetInfo(
    name='mnist',
    version=1.0.0,
    description='The MNIST database of handwritten digits.',
    homepage='http://yann.lecun.com/exdb/mnist/',
    features=FeaturesDict({
        'image': Image(shape=(28, 28, 1), dtype=tf.uint8),
        'label': ClassLabel(shape=(), dtype=tf.int64, num_classes=10),
    }),
    total_num_examples=70000,
    splits={
        'test': 10000,
        'train': 60000,
    },
    supervised_keys=('image', 'label'),
    citation="""@article{lecun2010mnist,
      title={MNIST handwritten digit database},
      author={LeCun, Yann and Cortes, Corinna and Burges, CJ},
      journal={ATT Labs [Online]. Available: http://yann. lecun. com/exdb/mnist},
      volume={2},
      year={2010}
    }""",
    redistribution_info=,
)

In [13]:
ds_dict = dd.read(conf_dict)

root dir set to ../datasets/tfd
W0105 07:01:00.209745 140369035720512 dataset_builder.py:327] Dataset mnist is hosted on GCS. It will automatically be downloaded to your
local data directory. If you'd instead prefer to read directly from our public
GCS bucket (recommended if you're running on GCP), you can instead set
data_dir=gs://tfds-data/datasets.





Dataset mnist downloaded and prepared to ../datasets/tfd/mnist/1.0.0. Subsequent calls will reuse this data.


In [8]:
ds_dict

{'train': <PrefetchDataset shapes: ((28, 28, 1), ()), types: (tf.uint8, tf.int64)>,
 'val': <PrefetchDataset shapes: ((28, 28, 1), ()), types: (tf.uint8, tf.int64)>,
 'test': <PrefetchDataset shapes: ((28, 28, 1), ()), types: (tf.uint8, tf.int64)>}

In [10]:
tds = ds_dict['train']

In [11]:
sing = tds.take(1)

In [17]:
for x,y in sing:
    print(x)
    print(y)

tf.Tensor(
[[[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  