In [1]:
%load_ext autoreload
%autoreload 2

import tensorflow as tf
import dataduit as dd

import pandas as pd

In [2]:
from pandas_dev import conf_dict
conf_dict

{'meta': {'name': 'albalone',
  'logging': {'log_stream_level': 'INFO'},
  'in': {'from': 'memory', 'type': 'pandas'}},
 'read': {'split_percents': [75, 15, 10],
  'split_names': ['train', 'val', 'test'],
  'iterate': {'return_type': 'tuple',
   'schema': {'x': {'length': {'indicator': 'length',
      'datatype': {'in': {'type': 'FixedLenFeature',
        'options': {'dtype': 'float64', 'shape': 1}},
       'out': {}},
      'special': 'decode'},
     'diameter': {'indicator': 'diameter',
      'datatype': {'in': {'type': 'FixedLenFeature',
        'options': {'dtype': 'float64', 'shape': 1}},
       'out': {}},
      'special': 'decode'}},
    'y': {'rings': {'datatype': {'in': {'type': 'FixedLenFeature',
        'options': {'dtype': 'int64', 'shape': 1}},
       'out': {}}}}}}}}

In [3]:
h = ["sex",
"length",
"diameter",
"height",
"whole_weight",
"shucked_weight",
"viscera_weight",
"shell_weight",
"rings"]
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/abalone/abalone.data',names=h)

In [4]:
df.iloc[0]

sex                    M
length             0.455
diameter           0.365
height             0.095
whole_weight       0.514
shucked_weight    0.2245
viscera_weight     0.101
shell_weight        0.15
rings                 15
Name: 0, dtype: object

In [5]:
df

sex  length  diameter  height  whole_weight  shucked_weight  \
0      M   0.455     0.365   0.095        0.5140          0.2245   
1      M   0.350     0.265   0.090        0.2255          0.0995   
2      F   0.530     0.420   0.135        0.6770          0.2565   
3      M   0.440     0.365   0.125        0.5160          0.2155   
4      I   0.330     0.255   0.080        0.2050          0.0895   
...   ..     ...       ...     ...           ...             ...   
4172   F   0.565     0.450   0.165        0.8870          0.3700   
4173   M   0.590     0.440   0.135        0.9660          0.4390   
4174   M   0.600     0.475   0.205        1.1760          0.5255   
4175   F   0.625     0.485   0.150        1.0945          0.5310   
4176   M   0.710     0.555   0.195        1.9485          0.9455   

      viscera_weight  shell_weight  rings  
0             0.1010        0.1500     15  
1             0.0485        0.0700      7  
2             0.1415        0.2100      9  
3             0.1140        0.1550     10  
4             0.0395        0.0550      7  
...              ...           ...    ...  
4172          0.2390        0.2490     11  
4173          0.2145        0.2605     10  
4174          0.2875        0.3080      9  
4175          0.2610        0.2960     10  
4176          0.3765        0.4950     12  

[4177 rows x 9 columns]

In [6]:
ds_dict = dd.read(conf_dict, df)

In [7]:
tds = ds_dict['train']
sing = tds.take(9)

In [8]:
# # if a return type is a dict
# for o in sing:
#     print(o['x']['length'])
#     print(o['x']['diameter'])
#     print(f"> {o['y']['rings']}")
#     print("-"*20)


# if return type is a tuple
for o in sing:
    print(o[0][0])
    print(o[0][1])
    print(f"> {o[1][0]}")
    print("-"*20)

tf.Tensor([0.605], shape=(1,), dtype=float64)
tf.Tensor([0.455], shape=(1,), dtype=float64)
> [9]
--------------------
tf.Tensor([0.59], shape=(1,), dtype=float64)
tf.Tensor([0.44], shape=(1,), dtype=float64)
> [8]
--------------------
tf.Tensor([0.56], shape=(1,), dtype=float64)
tf.Tensor([0.445], shape=(1,), dtype=float64)
> [16]
--------------------
tf.Tensor([0.635], shape=(1,), dtype=float64)
tf.Tensor([0.49], shape=(1,), dtype=float64)
> [9]
--------------------
tf.Tensor([0.475], shape=(1,), dtype=float64)
tf.Tensor([0.385], shape=(1,), dtype=float64)
> [14]
--------------------
tf.Tensor([0.52], shape=(1,), dtype=float64)
tf.Tensor([0.38], shape=(1,), dtype=float64)
> [11]
--------------------
tf.Tensor([0.52], shape=(1,), dtype=float64)
tf.Tensor([0.39], shape=(1,), dtype=float64)
> [7]
--------------------
tf.Tensor([0.48], shape=(1,), dtype=float64)
tf.Tensor([0.375], shape=(1,), dtype=float64)
> [6]
--------------------
tf.Tensor([0.365], shape=(1,), dtype=float64)
tf.Tenso